version: 2
jobs:
  build-with-gnutls:
    docker:
      - image: ubuntu:trusty
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get -y install build-essential
      - run: sudo apt-get -y install libelf-dev
      - run: sudo apt-get -y install wget
      - run: sudo apt-get -y install unzip
      - run: make config="--with-gnutls" without_ssl
  build-with-cyassl:
    docker:
      - image: ubuntu:trusty
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get -y install build-essential
      - run: sudo apt-get -y install libelf-dev
      - run: sudo apt-get -y install wget
      - run: sudo apt-get -y install unzip
      - run: make config="--with-cyassl" without_ssl
  build-with-nss:
    docker:
      - image: ubuntu:trusty
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get -y install build-essential
      - run: sudo apt-get -y install libelf-dev
      - run: sudo apt-get -y install wget
      - run: sudo apt-get -y install unzip
      - run: make config="--with-nss" without_ssl
  build-with-polarssl:
    docker:
      - image: ubuntu:trusty
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get -y install build-essential
      - run: sudo apt-get -y install libelf-dev
      - run: sudo apt-get -y install wget
      - run: sudo apt-get -y install unzip
      - run: make config="--with-polarssl" without_ssl
workflows:
  version: 2
  libcurl_builds:
    jobs:
      - build-with-gnutls
      - build-with-cyassl
      - build-with-nss
      - build-with-polarssl

